stages:
  - production

compile:
  image: aergus/latex
  stage: production
  only:
    refs:
      - master
  script:
    - git clone https://github.com/DPDmancul/Apple-Emoji.git
    - mv Apple-Emoji/* .
    - mkdir pdf
    - cd pdf
    - for i in ../Lezione*.tex ../testo.tex ; do pdflatex "$i";pdflatex "$i";pdflatex "$i"; done
  artifacts:
    paths:
      - pdf/*.pdf
